// Exportar componentes del módulo infrastructure
export { InfrastructureStats } from './InfrastructureStats';
export { ServerCard } from './ServerCard';
export { LicenseCard } from './LicenseCard';
export { StorageCard } from './StorageCard';
export { SoftwareCard } from './SoftwareCard';
export { ResourceCard } from './ResourceCard';
export { InfrastructureLayout } from './InfrastructureLayout';
export { ServerDetailsModal } from './ServerDetailsModal';
export { ServerFormModal } from './ServerFormModal';
export { DeleteServerModal } from './DeleteServerModal';
export { LicenseDetailsModal } from './LicenseDetailsModal';
export { LicenseFormModal } from './LicenseFormModal';
export { DeleteLicenseModal } from './DeleteLicenseModal';
