// Datos Mock para el módulo LMS
// Estos datos simulan las respuestas de la API
import type {
  LMSStats,
  RecentCourse,
  RecentEnrollment,
  Course,
  Student,
  Instructor,
  Enrollment,
} from '../types';

// Mock Stats
export const mockLMSStats: LMSStats = {
  total_courses: 477,
  published_courses: 38,
  draft_courses: 7,
  total_students: 1250,
  active_enrollments: 3420,
  total_instructors: 28,
};

// Mock Recent Courses
export const mockRecentCourses: RecentCourse[] = [
  {
    id: '1',
    title: 'Desarrollo Web Full Stack',
    code: 'WEB-101',
    instructor_name: 'Juan Pérez',
    status: 'publicado',
    created_at: '2024-03-15',
  },
  {
    id: '2',
    title: 'Inteligencia Artificial',
    code: 'IA-201',
    instructor_name: 'María González',
    status: 'publicado',
    created_at: '2024-03-14',
  },
  {
    id: '3',
    title: 'Diseño UX/UI',
    code: 'DIS-150',
    instructor_name: 'Carlos Ruiz',
    status: 'borrador',
    created_at: '2024-03-13',
  },
];

// Mock Recent Enrollments
export const mockRecentEnrollments: RecentEnrollment[] = [
  {
    id: '1',
    student_name: 'Ana Torres',
    student_email: 'ana.torres@email.com',
    course_title: 'Desarrollo Web Full Stack',
    enrolled_at: '2024-03-15 10:30:00',
  },
  {
    id: '2',
    student_name: 'Pedro Sánchez',
    student_email: 'pedro.sanchez@email.com',
    course_title: 'Inteligencia Artificial',
    enrolled_at: '2024-03-15 09:15:00',
  },
  {
    id: '3',
    student_name: 'Laura Martínez',
    student_email: 'laura.martinez@email.com',
    course_title: 'Diseño UX/UI',
    enrolled_at: '2024-03-14 16:45:00',
  },
];

// Mock Courses
export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Desarrollo Web Full Stack',
    code: 'WEB-101',
    description: 'Aprende a desarrollar aplicaciones web desde cero con las últimas tecnologías.',
    instructor_id: '1',
    duration_weeks: 12,
    price: 1500,
    status: 'publicado',
    created_at: '2024-01-15',
    updated_at: '2024-03-10',
  },
  {
    id: '2',
    title: 'Inteligencia Artificial',
    code: 'IA-201',
    description: 'Curso avanzado de IA, Machine Learning y Deep Learning.',
    instructor_id: '2',
    duration_weeks: 16,
    price: 2000,
    status: 'publicado',
    created_at: '2024-01-20',
    updated_at: '2024-03-08',
  },
  {
    id: '3',
    title: 'Diseño UX/UI',
    code: 'DIS-150',
    description: 'Diseña interfaces atractivas y funcionales centradas en el usuario.',
    instructor_id: '3',
    duration_weeks: 8,
    price: 1200,
    status: 'borrador',
    created_at: '2024-02-01',
    updated_at: '2024-03-12',
  },
    {
    id: '4',
    title: 'HEllo world',
    code: 'DIS-150',
    description: 'Diseña interfaces atractivas y funcionales centradas en el usuario.',
    instructor_id: '3',
    duration_weeks: 8,
    price: 1200,
    status: 'borrador',
    created_at: '2024-02-01',
    updated_at: '2024-03-12',
  },
];

// Mock Students
export const mockStudents: Student[] = [
  {
    id: '1',
    first_name: 'Ana',
    last_name: 'Torres',
    email: 'ana.torres@email.com',
    email_verified_at: '2024-01-15',
    address: 'Av. Arequipa 1234, Lima',
    birth_date: '2000-05-15',
    gender: 'F',
    country_location: 'PE',
    profile_photo: null,
    role: 'student',
    state: 'activo',
    last_access_ip: '192.168.1.1',
    last_access: '2024-03-15 10:30:00',
    created_at: '2024-01-01',
    updated_at: '2024-03-15',
  },
  {
    id: '2',
    first_name: 'Pedro',
    last_name: 'Sánchez',
    email: 'pedro.sanchez@email.com',
    email_verified_at: '2024-01-20',
    address: 'Jr. Lampa 567, Lima',
    birth_date: '1998-08-20',
    gender: 'M',
    country_location: 'PE',
    profile_photo: null,
    role: 'student',
    state: 'activo',
    last_access_ip: '192.168.1.2',
    last_access: '2024-03-15 09:15:00',
    created_at: '2024-01-05',
    updated_at: '2024-03-15',
  },
  {
    id: '3',
    first_name: 'Laura',
    last_name: 'Martínez',
    email: 'laura.martinez@email.com',
    email_verified_at: '2024-02-01',
    address: 'Av. Colonial 890, Lima',
    birth_date: '1999-11-10',
    gender: 'F',
    country_location: 'PE',
    profile_photo: null,
    role: 'student',
    state: 'activo',
    last_access_ip: '192.168.1.3',
    last_access: '2024-03-14 16:45:00',
    created_at: '2024-01-10',
    updated_at: '2024-03-14',
  },
  {
    id: '4',
    first_name: 'Carlos',
    last_name: 'Rojas',
    email: 'carlos.rojas@email.com',
    email_verified_at: '2024-02-05',
    address: 'Jr. Cusco 234, Lima',
    birth_date: '2001-03-22',
    gender: 'M',
    country_location: 'PE',
    profile_photo: null,
    role: 'student',
    state: 'activo',
    last_access_ip: '192.168.1.4',
    last_access: '2024-03-14 11:20:00',
    created_at: '2024-01-15',
    updated_at: '2024-03-14',
  },
];

// Mock Instructors
export const mockInstructors: Instructor[] = [
  {
    id: '1',
    first_name: 'Juan',
    last_name: 'Pérez',
    email: 'juan.perez@email.com',
    email_verified_at: '2024-01-10',
    address: 'Av. Universitaria 456, Lima',
    birth_date: '1985-03-15',
    gender: 'M',
    country_location: 'PE',
    profile_photo: null,
    role: 'instructor',
    state: 'activo',
    last_access_ip: '192.168.1.10',
    last_access: '2024-03-15 14:20:00',
    created_at: '2023-12-01',
    updated_at: '2024-03-15',
    bio: 'Desarrollador Full Stack con más de 10 años de experiencia en tecnologías web.',
    expertise_area: 'Desarrollo Web, JavaScript, React, Node.js',
    status: 'activo',
  },
  {
    id: '2',
    first_name: 'María',
    last_name: 'González',
    email: 'maria.gonzalez@email.com',
    email_verified_at: '2024-01-12',
    address: 'Av. Javier Prado 890, Lima',
    birth_date: '1988-07-22',
    gender: 'F',
    country_location: 'PE',
    profile_photo: null,
    role: 'instructor',
    state: 'activo',
    last_access_ip: '192.168.1.11',
    last_access: '2024-03-15 13:45:00',
    created_at: '2023-12-05',
    updated_at: '2024-03-15',
    bio: 'Especialista en Inteligencia Artificial y Machine Learning con PhD en Ciencias de la Computación.',
    expertise_area: 'Inteligencia Artificial, Machine Learning, Python',
    status: 'activo',
  },
];

// Mock Enrollments
export const mockEnrollments: Enrollment[] = [
  {
    id: '1',
    student_id: '1',
    course_id: '1',
    enrolled_at: '2024-03-15 10:30:00',
    status: 'activo',
    progress: 45,
  },
  {
    id: '2',
    student_id: '2',
    course_id: '2',
    enrolled_at: '2024-03-15 09:15:00',
    status: 'activo',
    progress: 30,
  },
  {
    id: '3',
    student_id: '3',
    course_id: '1',
    enrolled_at: '2024-03-14 16:45:00',
    status: 'activo',
    progress: 78,
  },
  {
    id: '4',
    student_id: '4',
    course_id: '1',
    enrolled_at: '2024-03-10 08:20:00',
    status: 'completado',
    progress: 100,
  },
  {
    id: '5',
    student_id: '2',
    course_id: '1',
    enrolled_at: '2024-02-20 14:15:00',
    status: 'abandonado',
    progress: 15,
  },
];
