// Exportar componentes del módulo lms
export { LMSStatsCard } from './LMSStatsCard';
export { RecentCourseCard } from './RecentCourseCard';
export { RecentEnrollmentCard } from './RecentEnrollmentCard';
export { CreateCourseModal } from './CreateCourseModal';
export { LMSLayout } from './LMSLayout';
export { CourseCard } from './CourseCard';
export { ViewCourseModal } from './ViewCourseModal';
export { EditStudentModal } from './EditStudentModal';
export { ViewStudentModal } from './ViewStudentModal';
export { EditInstructorModal } from './EditInstructorModal';
