export { AnalyticsPage } from './AnalyticsPage';
export { AnalyticsMainPage } from './AnalyticsMainPage';
export { AnalyticsDashboardPage } from './AnalyticsDashboardPage';
export { AttendancePage } from './AttendancePage';
export { AttendanceAnalyticsPage } from './AttendanceAnalyticsPage';
export { ProgressPage } from './ProgressPage';
export { PerformancePage } from './PerformancePage';
export { DropoutPage } from './DropoutPage';
export { ReportsPage } from './ReportsPage';
